namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmChuyenLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.txtMa = new System.Windows.Forms.TextBox();
            txtMa.Name = "txtMa";
            txtMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.cboTour = new System.Windows.Forms.ComboBox();
            cboTour.Name = "cboTour";
            cboTour.Dock = System.Windows.Forms.DockStyle.Fill;
            cboTour.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dtDi = new System.Windows.Forms.DateTimePicker();
            dtDi.Name = "dtDi";
            dtDi.Dock = System.Windows.Forms.DockStyle.Fill;
            dtDi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtDi.CustomFormat = "dd/MM/yyyy";
            this.lblNgayVe = new System.Windows.Forms.Label();
            lblNgayVe.Name = "lblNgayVe";
            lblNgayVe.Dock = System.Windows.Forms.DockStyle.Fill;
            lblNgayVe.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            lblNgayVe.Text = "-";
            lblNgayVe.AutoSize = true;
            this.txtDon = new System.Windows.Forms.TextBox();
            txtDon.Name = "txtDon";
            txtDon.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDon.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThem = new System.Windows.Forms.Button();
            btnThem.Name = "btnThem";
            btnThem.Text = "Tạo chuyến";
            btnThem.AutoSize = true;
            btnThem.MinimumSize = new System.Drawing.Size(145, 34);
            btnThem.Margin = new System.Windows.Forms.Padding(4);
            this.btnDongDK = new System.Windows.Forms.Button();
            btnDongDK.Name = "btnDongDK";
            btnDongDK.Text = "Đóng đăng ký";
            btnDongDK.AutoSize = true;
            btnDongDK.MinimumSize = new System.Drawing.Size(145, 34);
            btnDongDK.Margin = new System.Windows.Forms.Padding(4);
            this.dgv = new System.Windows.Forms.DataGridView();
            dgv.Name = "dgv";
            dgv.Dock = System.Windows.Forms.DockStyle.Top;
            dgv.Height = 185;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.AutoGenerateColumns = true;
            dgv.MultiSelect = false;
            dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.BackgroundColor = System.Drawing.Color.White;
            dgv.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            var fields3 = new System.Windows.Forms.TableLayoutPanel();
            fields3.Dock = System.Windows.Forms.DockStyle.Top;
            fields3.AutoSize = true;
            fields3.ColumnCount = 4;
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label4 = new System.Windows.Forms.Label();
            label4.Text = "Mã chuyến";
            label4.AutoSize = true;
            label4.Dock = System.Windows.Forms.DockStyle.Fill;
            label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label4.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label4, 0, 0);
            fields3.Controls.Add(txtMa, 1, 0);
            var label5 = new System.Windows.Forms.Label();
            label5.Text = "Tour";
            label5.AutoSize = true;
            label5.Dock = System.Windows.Forms.DockStyle.Fill;
            label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label5.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label5, 2, 0);
            fields3.Controls.Add(cboTour, 3, 0);
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Ngày đi";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label6, 0, 1);
            fields3.Controls.Add(dtDi, 1, 1);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Ngày về";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label7, 2, 1);
            fields3.Controls.Add(lblNgayVe, 3, 1);
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Địa điểm đón";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label8, 0, 2);
            fields3.Controls.Add(txtDon, 1, 2);
            layout2.Controls.Add(fields3);
            var actions9 = new System.Windows.Forms.FlowLayoutPanel();
            actions9.Dock = System.Windows.Forms.DockStyle.Top;
            actions9.AutoSize = true;
            actions9.Controls.Add(btnThem);
            actions9.Controls.Add(btnDongDK);
            actions9.Controls.Add(btnDong);
            layout2.Controls.Add(actions9);
            layout2.Controls.Add(dgv);
            this.cboTour.SelectedIndexChanged += this.TinhNgayVe;
            this.dtDi.ValueChanged += this.TinhNgayVe;
            this.btnThem.Click += this.btnThem_Click;
            this.btnDongDK.Click += this.btnDongDK_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmChuyenLe_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Lịch chuyến khách lẻ";
            this.Name = "FrmChuyenLe";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.TextBox txtMa;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.DateTimePicker dtDi;
        private System.Windows.Forms.Label lblNgayVe;
        private System.Windows.Forms.TextBox txtDon;
        private System.Windows.Forms.Button btnThem;
        private System.Windows.Forms.Button btnDongDK;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Button btnDong;
    }
}
