namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.grpDoan = new System.Windows.Forms.GroupBox();
            grpDoan.Name = "grpDoan";
            grpDoan.Text = "Thông tin đoàn khách";
            grpDoan.AutoSize = true;
            grpDoan.Dock = System.Windows.Forms.DockStyle.Top;
            grpDoan.Padding = new System.Windows.Forms.Padding(6, 20, 6, 6);
            this.txtMaDoan = new System.Windows.Forms.TextBox();
            txtMaDoan.Name = "txtMaDoan";
            txtMaDoan.Dock = System.Windows.Forms.DockStyle.Fill;
            txtMaDoan.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtTenCQ = new System.Windows.Forms.TextBox();
            txtTenCQ.Name = "txtTenCQ";
            txtTenCQ.Dock = System.Windows.Forms.DockStyle.Fill;
            txtTenCQ.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDiaChi = new System.Windows.Forms.TextBox();
            txtDiaChi.Name = "txtDiaChi";
            txtDiaChi.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDiaChi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDT = new System.Windows.Forms.TextBox();
            txtDT.Name = "txtDT";
            txtDT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDaiDien = new System.Windows.Forms.TextBox();
            txtDaiDien.Name = "txtDaiDien";
            txtDaiDien.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDaiDien.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.grpDangKy = new System.Windows.Forms.GroupBox();
            grpDangKy.Name = "grpDangKy";
            grpDangKy.Text = "Đăng ký tour";
            grpDangKy.AutoSize = true;
            grpDangKy.Dock = System.Windows.Forms.DockStyle.Top;
            grpDangKy.Padding = new System.Windows.Forms.Padding(6, 20, 6, 6);
            this.txtSo = new System.Windows.Forms.TextBox();
            txtSo.Name = "txtSo";
            txtSo.Dock = System.Windows.Forms.DockStyle.Fill;
            txtSo.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.cboTour = new System.Windows.Forms.ComboBox();
            cboTour.Name = "cboTour";
            cboTour.Dock = System.Windows.Forms.DockStyle.Fill;
            cboTour.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dtDi = new System.Windows.Forms.DateTimePicker();
            dtDi.Name = "dtDi";
            dtDi.Dock = System.Windows.Forms.DockStyle.Fill;
            dtDi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtDi.CustomFormat = "dd/MM/yyyy";
            this.numNguoi = new System.Windows.Forms.NumericUpDown();
            numNguoi.Name = "numNguoi";
            numNguoi.Dock = System.Windows.Forms.DockStyle.Fill;
            numNguoi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numNguoi.Maximum = 10000M;
            numNguoi.Minimum = 13M;
            numNguoi.Value = 13M;
            this.txtDon = new System.Windows.Forms.TextBox();
            txtDon.Name = "txtDon";
            txtDon.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDon.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            numCoc.Name = "numCoc";
            numCoc.Dock = System.Windows.Forms.DockStyle.Fill;
            numCoc.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numCoc.Maximum = 1000000000000M;
            numCoc.Minimum = 0M;
            numCoc.Value = 0M;
            numCoc.DecimalPlaces = 2;
            numCoc.ThousandsSeparator = true;
            this.chkBH = new System.Windows.Forms.CheckBox();
            chkBH.Name = "chkBH";
            chkBH.Dock = System.Windows.Forms.DockStyle.Fill;
            chkBH.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            chkBH.Text = "Mua bảo hiểm";
            chkBH.AutoSize = true;
            this.lblKetThuc = new System.Windows.Forms.Label();
            lblKetThuc.Name = "lblKetThuc";
            lblKetThuc.Dock = System.Windows.Forms.DockStyle.Fill;
            lblKetThuc.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            lblKetThuc.Text = "-";
            lblKetThuc.AutoSize = true;
            this.lblTong = new System.Windows.Forms.Label();
            lblTong.Name = "lblTong";
            lblTong.Dock = System.Windows.Forms.DockStyle.Fill;
            lblTong.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            lblTong.Text = "-";
            lblTong.AutoSize = true;
            this.dgvThanhVien = new System.Windows.Forms.DataGridView();
            dgvThanhVien.Name = "dgvThanhVien";
            dgvThanhVien.Dock = System.Windows.Forms.DockStyle.Top;
            dgvThanhVien.Height = 145;
            dgvThanhVien.ReadOnly = false;
            dgvThanhVien.AllowUserToAddRows = true;
            dgvThanhVien.AllowUserToDeleteRows = true;
            dgvThanhVien.AutoGenerateColumns = true;
            dgvThanhVien.MultiSelect = false;
            dgvThanhVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvThanhVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvThanhVien.BackgroundColor = System.Drawing.Color.White;
            dgvThanhVien.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.btnDangKy = new System.Windows.Forms.Button();
            btnDangKy.Name = "btnDangKy";
            btnDangKy.Text = "Lập phiếu đăng ký";
            btnDangKy.AutoSize = true;
            btnDangKy.MinimumSize = new System.Drawing.Size(145, 34);
            btnDangKy.Margin = new System.Windows.Forms.Padding(4);
            this.btnHuy = new System.Windows.Forms.Button();
            btnHuy.Name = "btnHuy";
            btnHuy.Text = "Hủy phiếu (mất cọc)";
            btnHuy.AutoSize = true;
            btnHuy.MinimumSize = new System.Drawing.Size(145, 34);
            btnHuy.Margin = new System.Windows.Forms.Padding(4);
            this.dgv = new System.Windows.Forms.DataGridView();
            dgv.Name = "dgv";
            dgv.Dock = System.Windows.Forms.DockStyle.Top;
            dgv.Height = 185;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.AutoGenerateColumns = true;
            dgv.MultiSelect = false;
            dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.BackgroundColor = System.Drawing.Color.White;
            dgv.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            layout2.Controls.Add(grpDoan);
            var layout3 = new System.Windows.Forms.TableLayoutPanel();
            layout3.Dock = System.Windows.Forms.DockStyle.Top;
            layout3.AutoSize = true;
            layout3.ColumnCount = 1;
            layout3.Padding = new System.Windows.Forms.Padding(12);
            layout3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            grpDoan.Controls.Add(layout3);
            var fields4 = new System.Windows.Forms.TableLayoutPanel();
            fields4.Dock = System.Windows.Forms.DockStyle.Top;
            fields4.AutoSize = true;
            fields4.ColumnCount = 4;
            fields4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label5 = new System.Windows.Forms.Label();
            label5.Text = "Mã đoàn";
            label5.AutoSize = true;
            label5.Dock = System.Windows.Forms.DockStyle.Fill;
            label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label5.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields4.Controls.Add(label5, 0, 0);
            fields4.Controls.Add(txtMaDoan, 1, 0);
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Cơ quan / gia đình";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields4.Controls.Add(label6, 2, 0);
            fields4.Controls.Add(txtTenCQ, 3, 0);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Địa chỉ";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields4.Controls.Add(label7, 0, 1);
            fields4.Controls.Add(txtDiaChi, 1, 1);
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Điện thoại";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields4.Controls.Add(label8, 2, 1);
            fields4.Controls.Add(txtDT, 3, 1);
            var label9 = new System.Windows.Forms.Label();
            label9.Text = "Người đại diện";
            label9.AutoSize = true;
            label9.Dock = System.Windows.Forms.DockStyle.Fill;
            label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label9.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields4.Controls.Add(label9, 0, 2);
            fields4.Controls.Add(txtDaiDien, 1, 2);
            layout3.Controls.Add(fields4);
            layout2.Controls.Add(grpDangKy);
            var layout10 = new System.Windows.Forms.TableLayoutPanel();
            layout10.Dock = System.Windows.Forms.DockStyle.Top;
            layout10.AutoSize = true;
            layout10.ColumnCount = 1;
            layout10.Padding = new System.Windows.Forms.Padding(12);
            layout10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            grpDangKy.Controls.Add(layout10);
            var fields11 = new System.Windows.Forms.TableLayoutPanel();
            fields11.Dock = System.Windows.Forms.DockStyle.Top;
            fields11.AutoSize = true;
            fields11.ColumnCount = 4;
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label12 = new System.Windows.Forms.Label();
            label12.Text = "Số phiếu";
            label12.AutoSize = true;
            label12.Dock = System.Windows.Forms.DockStyle.Fill;
            label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label12.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label12, 0, 0);
            fields11.Controls.Add(txtSo, 1, 0);
            var label13 = new System.Windows.Forms.Label();
            label13.Text = "Tour";
            label13.AutoSize = true;
            label13.Dock = System.Windows.Forms.DockStyle.Fill;
            label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label13.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label13, 2, 0);
            fields11.Controls.Add(cboTour, 3, 0);
            var label14 = new System.Windows.Forms.Label();
            label14.Text = "Ngày đi";
            label14.AutoSize = true;
            label14.Dock = System.Windows.Forms.DockStyle.Fill;
            label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label14.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label14, 0, 1);
            fields11.Controls.Add(dtDi, 1, 1);
            var label15 = new System.Windows.Forms.Label();
            label15.Text = "Số người";
            label15.AutoSize = true;
            label15.Dock = System.Windows.Forms.DockStyle.Fill;
            label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label15.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label15, 2, 1);
            fields11.Controls.Add(numNguoi, 3, 1);
            var label16 = new System.Windows.Forms.Label();
            label16.Text = "Địa điểm đón";
            label16.AutoSize = true;
            label16.Dock = System.Windows.Forms.DockStyle.Fill;
            label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label16.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label16, 0, 2);
            fields11.Controls.Add(txtDon, 1, 2);
            var label17 = new System.Windows.Forms.Label();
            label17.Text = "Tiền cọc";
            label17.AutoSize = true;
            label17.Dock = System.Windows.Forms.DockStyle.Fill;
            label17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label17.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label17, 2, 2);
            fields11.Controls.Add(numCoc, 3, 2);
            var label18 = new System.Windows.Forms.Label();
            label18.Text = "Mua bảo hiểm";
            label18.AutoSize = true;
            label18.Dock = System.Windows.Forms.DockStyle.Fill;
            label18.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label18.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label18, 0, 3);
            fields11.Controls.Add(chkBH, 1, 3);
            var label19 = new System.Windows.Forms.Label();
            label19.Text = "Kết thúc DK";
            label19.AutoSize = true;
            label19.Dock = System.Windows.Forms.DockStyle.Fill;
            label19.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label19.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label19, 2, 3);
            fields11.Controls.Add(lblKetThuc, 3, 3);
            var label20 = new System.Windows.Forms.Label();
            label20.Text = "Tổng dự kiến";
            label20.AutoSize = true;
            label20.Dock = System.Windows.Forms.DockStyle.Fill;
            label20.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label20.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label20, 0, 4);
            fields11.Controls.Add(lblTong, 1, 4);
            layout10.Controls.Add(fields11);
            var actions21 = new System.Windows.Forms.FlowLayoutPanel();
            actions21.Dock = System.Windows.Forms.DockStyle.Top;
            actions21.AutoSize = true;
            actions21.Controls.Add(btnDangKy);
            actions21.Controls.Add(btnHuy);
            actions21.Controls.Add(btnDong);
            layout2.Controls.Add(actions21);
            layout2.Controls.Add(dgvThanhVien);
            layout2.Controls.Add(dgv);
            this.cboTour.SelectedIndexChanged += this.TinhTong;
            this.dtDi.ValueChanged += this.TinhTong;
            this.numNguoi.ValueChanged += this.TinhTong;
            this.chkBH.CheckedChanged += this.chkBH_CheckedChanged;
            this.btnDangKy.Click += this.btnDangKy_Click;
            this.btnHuy.Click += this.btnHuy_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmDangKyDoan_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Đăng ký theo đoàn";
            this.Name = "FrmDangKyDoan";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.GroupBox grpDoan;
        private System.Windows.Forms.TextBox txtMaDoan;
        private System.Windows.Forms.TextBox txtTenCQ;
        private System.Windows.Forms.TextBox txtDiaChi;
        private System.Windows.Forms.TextBox txtDT;
        private System.Windows.Forms.TextBox txtDaiDien;
        private System.Windows.Forms.GroupBox grpDangKy;
        private System.Windows.Forms.TextBox txtSo;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.DateTimePicker dtDi;
        private System.Windows.Forms.NumericUpDown numNguoi;
        private System.Windows.Forms.TextBox txtDon;
        private System.Windows.Forms.NumericUpDown numCoc;
        private System.Windows.Forms.CheckBox chkBH;
        private System.Windows.Forms.Label lblKetThuc;
        private System.Windows.Forms.Label lblTong;
        private System.Windows.Forms.DataGridView dgvThanhVien;
        private System.Windows.Forms.Button btnDangKy;
        private System.Windows.Forms.Button btnHuy;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Button btnDong;
    }
}
