namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabDanhMuc = new System.Windows.Forms.TabControl();
            tabDanhMuc.Name = "tabDanhMuc";
            tabDanhMuc.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvPT = new System.Windows.Forms.DataGridView();
            dgvPT.Name = "dgvPT";
            dgvPT.Dock = System.Windows.Forms.DockStyle.Top;
            dgvPT.Height = 185;
            dgvPT.ReadOnly = true;
            dgvPT.AllowUserToAddRows = false;
            dgvPT.AllowUserToDeleteRows = false;
            dgvPT.AutoGenerateColumns = true;
            dgvPT.MultiSelect = false;
            dgvPT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvPT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvPT.BackgroundColor = System.Drawing.Color.White;
            dgvPT.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtPTMa = new System.Windows.Forms.TextBox();
            txtPTMa.Name = "txtPTMa";
            txtPTMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtPTMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtPTTen = new System.Windows.Forms.TextBox();
            txtPTTen.Name = "txtPTTen";
            txtPTTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtPTTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtPTGhiChu = new System.Windows.Forms.TextBox();
            txtPTGhiChu.Name = "txtPTGhiChu";
            txtPTGhiChu.Dock = System.Windows.Forms.DockStyle.Fill;
            txtPTGhiChu.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemPT = new System.Windows.Forms.Button();
            btnThemPT.Name = "btnThemPT";
            btnThemPT.Text = "Thêm";
            btnThemPT.AutoSize = true;
            btnThemPT.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemPT.Margin = new System.Windows.Forms.Padding(4);
            this.dgvDB = new System.Windows.Forms.DataGridView();
            dgvDB.Name = "dgvDB";
            dgvDB.Dock = System.Windows.Forms.DockStyle.Top;
            dgvDB.Height = 185;
            dgvDB.ReadOnly = true;
            dgvDB.AllowUserToAddRows = false;
            dgvDB.AllowUserToDeleteRows = false;
            dgvDB.AutoGenerateColumns = true;
            dgvDB.MultiSelect = false;
            dgvDB.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvDB.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvDB.BackgroundColor = System.Drawing.Color.White;
            dgvDB.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtDBMa = new System.Windows.Forms.TextBox();
            txtDBMa.Name = "txtDBMa";
            txtDBMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDBMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDBTen = new System.Windows.Forms.TextBox();
            txtDBTen.Name = "txtDBTen";
            txtDBTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDBTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDBDiaChi = new System.Windows.Forms.TextBox();
            txtDBDiaChi.Name = "txtDBDiaChi";
            txtDBDiaChi.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDBDiaChi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDBDT = new System.Windows.Forms.TextBox();
            txtDBDT.Name = "txtDBDT";
            txtDBDT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDBDT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemDB = new System.Windows.Forms.Button();
            btnThemDB.Name = "btnThemDB";
            btnThemDB.Text = "Thêm";
            btnThemDB.AutoSize = true;
            btnThemDB.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemDB.Margin = new System.Windows.Forms.Padding(4);
            this.dgvHDV = new System.Windows.Forms.DataGridView();
            dgvHDV.Name = "dgvHDV";
            dgvHDV.Dock = System.Windows.Forms.DockStyle.Top;
            dgvHDV.Height = 185;
            dgvHDV.ReadOnly = true;
            dgvHDV.AllowUserToAddRows = false;
            dgvHDV.AllowUserToDeleteRows = false;
            dgvHDV.AutoGenerateColumns = true;
            dgvHDV.MultiSelect = false;
            dgvHDV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvHDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvHDV.BackgroundColor = System.Drawing.Color.White;
            dgvHDV.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtHDVMa = new System.Windows.Forms.TextBox();
            txtHDVMa.Name = "txtHDVMa";
            txtHDVMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtHDVMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtHDVTen = new System.Windows.Forms.TextBox();
            txtHDVTen.Name = "txtHDVTen";
            txtHDVTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtHDVTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtHDVDT = new System.Windows.Forms.TextBox();
            txtHDVDT.Name = "txtHDVDT";
            txtHDVDT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtHDVDT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.numLuong = new System.Windows.Forms.NumericUpDown();
            numLuong.Name = "numLuong";
            numLuong.Dock = System.Windows.Forms.DockStyle.Fill;
            numLuong.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numLuong.Maximum = 1000000000000M;
            numLuong.Minimum = 0M;
            numLuong.Value = 0M;
            numLuong.DecimalPlaces = 2;
            numLuong.ThousandsSeparator = true;
            this.btnThemHDV = new System.Windows.Forms.Button();
            btnThemHDV.Name = "btnThemHDV";
            btnThemHDV.Text = "Thêm";
            btnThemHDV.AutoSize = true;
            btnThemHDV.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemHDV.Margin = new System.Windows.Forms.Padding(4);
            this.dgvDTQ = new System.Windows.Forms.DataGridView();
            dgvDTQ.Name = "dgvDTQ";
            dgvDTQ.Dock = System.Windows.Forms.DockStyle.Top;
            dgvDTQ.Height = 185;
            dgvDTQ.ReadOnly = true;
            dgvDTQ.AllowUserToAddRows = false;
            dgvDTQ.AllowUserToDeleteRows = false;
            dgvDTQ.AutoGenerateColumns = true;
            dgvDTQ.MultiSelect = false;
            dgvDTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvDTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvDTQ.BackgroundColor = System.Drawing.Color.White;
            dgvDTQ.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtDTQMa = new System.Windows.Forms.TextBox();
            txtDTQMa.Name = "txtDTQMa";
            txtDTQMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDTQMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDTQTen = new System.Windows.Forms.TextBox();
            txtDTQTen.Name = "txtDTQTen";
            txtDTQTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDTQTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDTQDiaDiem = new System.Windows.Forms.TextBox();
            txtDTQDiaDiem.Name = "txtDTQDiaDiem";
            txtDTQDiaDiem.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDTQDiaDiem.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDTQNoiDung = new System.Windows.Forms.TextBox();
            txtDTQNoiDung.Name = "txtDTQNoiDung";
            txtDTQNoiDung.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDTQNoiDung.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDTQYNghia = new System.Windows.Forms.TextBox();
            txtDTQYNghia.Name = "txtDTQYNghia";
            txtDTQYNghia.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDTQYNghia.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemDTQ = new System.Windows.Forms.Button();
            btnThemDTQ.Name = "btnThemDTQ";
            btnThemDTQ.Text = "Thêm";
            btnThemDTQ.AutoSize = true;
            btnThemDTQ.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemDTQ.Margin = new System.Windows.Forms.Padding(4);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            tabDanhMuc.Dock = System.Windows.Forms.DockStyle.Top;
            tabDanhMuc.Height = 610;
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            layout2.Controls.Add(tabDanhMuc);
            var page3 = new System.Windows.Forms.TabPage();
            page3.Text = "Phương tiện";
            page3.AutoScroll = true;
            tabDanhMuc.Controls.Add(page3);
            var layout4 = new System.Windows.Forms.TableLayoutPanel();
            layout4.Dock = System.Windows.Forms.DockStyle.Top;
            layout4.AutoSize = true;
            layout4.ColumnCount = 1;
            layout4.Padding = new System.Windows.Forms.Padding(12);
            layout4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page3.Controls.Add(layout4);
            var fields5 = new System.Windows.Forms.TableLayoutPanel();
            fields5.Dock = System.Windows.Forms.DockStyle.Top;
            fields5.AutoSize = true;
            fields5.ColumnCount = 4;
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Mã PT";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label6, 0, 0);
            fields5.Controls.Add(txtPTMa, 1, 0);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Tên PT";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label7, 2, 0);
            fields5.Controls.Add(txtPTTen, 3, 0);
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Ghi chú";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label8, 0, 1);
            fields5.Controls.Add(txtPTGhiChu, 1, 1);
            layout4.Controls.Add(fields5);
            var actions9 = new System.Windows.Forms.FlowLayoutPanel();
            actions9.Dock = System.Windows.Forms.DockStyle.Top;
            actions9.AutoSize = true;
            actions9.Controls.Add(btnThemPT);
            layout4.Controls.Add(actions9);
            layout4.Controls.Add(dgvPT);
            var page10 = new System.Windows.Forms.TabPage();
            page10.Text = "Điểm bán vé";
            page10.AutoScroll = true;
            tabDanhMuc.Controls.Add(page10);
            var layout11 = new System.Windows.Forms.TableLayoutPanel();
            layout11.Dock = System.Windows.Forms.DockStyle.Top;
            layout11.AutoSize = true;
            layout11.ColumnCount = 1;
            layout11.Padding = new System.Windows.Forms.Padding(12);
            layout11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page10.Controls.Add(layout11);
            var fields12 = new System.Windows.Forms.TableLayoutPanel();
            fields12.Dock = System.Windows.Forms.DockStyle.Top;
            fields12.AutoSize = true;
            fields12.ColumnCount = 4;
            fields12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label13 = new System.Windows.Forms.Label();
            label13.Text = "Mã điểm bán";
            label13.AutoSize = true;
            label13.Dock = System.Windows.Forms.DockStyle.Fill;
            label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label13.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields12.Controls.Add(label13, 0, 0);
            fields12.Controls.Add(txtDBMa, 1, 0);
            var label14 = new System.Windows.Forms.Label();
            label14.Text = "Tên điểm bán";
            label14.AutoSize = true;
            label14.Dock = System.Windows.Forms.DockStyle.Fill;
            label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label14.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields12.Controls.Add(label14, 2, 0);
            fields12.Controls.Add(txtDBTen, 3, 0);
            var label15 = new System.Windows.Forms.Label();
            label15.Text = "Địa chỉ";
            label15.AutoSize = true;
            label15.Dock = System.Windows.Forms.DockStyle.Fill;
            label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label15.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields12.Controls.Add(label15, 0, 1);
            fields12.Controls.Add(txtDBDiaChi, 1, 1);
            var label16 = new System.Windows.Forms.Label();
            label16.Text = "Điện thoại";
            label16.AutoSize = true;
            label16.Dock = System.Windows.Forms.DockStyle.Fill;
            label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label16.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields12.Controls.Add(label16, 2, 1);
            fields12.Controls.Add(txtDBDT, 3, 1);
            layout11.Controls.Add(fields12);
            var actions17 = new System.Windows.Forms.FlowLayoutPanel();
            actions17.Dock = System.Windows.Forms.DockStyle.Top;
            actions17.AutoSize = true;
            actions17.Controls.Add(btnThemDB);
            layout11.Controls.Add(actions17);
            layout11.Controls.Add(dgvDB);
            var page18 = new System.Windows.Forms.TabPage();
            page18.Text = "Hướng dẫn viên";
            page18.AutoScroll = true;
            tabDanhMuc.Controls.Add(page18);
            var layout19 = new System.Windows.Forms.TableLayoutPanel();
            layout19.Dock = System.Windows.Forms.DockStyle.Top;
            layout19.AutoSize = true;
            layout19.ColumnCount = 1;
            layout19.Padding = new System.Windows.Forms.Padding(12);
            layout19.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page18.Controls.Add(layout19);
            var fields20 = new System.Windows.Forms.TableLayoutPanel();
            fields20.Dock = System.Windows.Forms.DockStyle.Top;
            fields20.AutoSize = true;
            fields20.ColumnCount = 4;
            fields20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label21 = new System.Windows.Forms.Label();
            label21.Text = "Mã HDV";
            label21.AutoSize = true;
            label21.Dock = System.Windows.Forms.DockStyle.Fill;
            label21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label21.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields20.Controls.Add(label21, 0, 0);
            fields20.Controls.Add(txtHDVMa, 1, 0);
            var label22 = new System.Windows.Forms.Label();
            label22.Text = "Họ tên";
            label22.AutoSize = true;
            label22.Dock = System.Windows.Forms.DockStyle.Fill;
            label22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label22.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields20.Controls.Add(label22, 2, 0);
            fields20.Controls.Add(txtHDVTen, 3, 0);
            var label23 = new System.Windows.Forms.Label();
            label23.Text = "Điện thoại";
            label23.AutoSize = true;
            label23.Dock = System.Windows.Forms.DockStyle.Fill;
            label23.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label23.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields20.Controls.Add(label23, 0, 1);
            fields20.Controls.Add(txtHDVDT, 1, 1);
            var label24 = new System.Windows.Forms.Label();
            label24.Text = "Lương căn bản";
            label24.AutoSize = true;
            label24.Dock = System.Windows.Forms.DockStyle.Fill;
            label24.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label24.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields20.Controls.Add(label24, 2, 1);
            fields20.Controls.Add(numLuong, 3, 1);
            layout19.Controls.Add(fields20);
            var actions25 = new System.Windows.Forms.FlowLayoutPanel();
            actions25.Dock = System.Windows.Forms.DockStyle.Top;
            actions25.AutoSize = true;
            actions25.Controls.Add(btnThemHDV);
            layout19.Controls.Add(actions25);
            layout19.Controls.Add(dgvHDV);
            var page26 = new System.Windows.Forms.TabPage();
            page26.Text = "Điểm tham quan";
            page26.AutoScroll = true;
            tabDanhMuc.Controls.Add(page26);
            var layout27 = new System.Windows.Forms.TableLayoutPanel();
            layout27.Dock = System.Windows.Forms.DockStyle.Top;
            layout27.AutoSize = true;
            layout27.ColumnCount = 1;
            layout27.Padding = new System.Windows.Forms.Padding(12);
            layout27.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page26.Controls.Add(layout27);
            var fields28 = new System.Windows.Forms.TableLayoutPanel();
            fields28.Dock = System.Windows.Forms.DockStyle.Top;
            fields28.AutoSize = true;
            fields28.ColumnCount = 4;
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label29 = new System.Windows.Forms.Label();
            label29.Text = "Mã điểm TQ";
            label29.AutoSize = true;
            label29.Dock = System.Windows.Forms.DockStyle.Fill;
            label29.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label29.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label29, 0, 0);
            fields28.Controls.Add(txtDTQMa, 1, 0);
            var label30 = new System.Windows.Forms.Label();
            label30.Text = "Tên điểm TQ";
            label30.AutoSize = true;
            label30.Dock = System.Windows.Forms.DockStyle.Fill;
            label30.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label30.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label30, 2, 0);
            fields28.Controls.Add(txtDTQTen, 3, 0);
            var label31 = new System.Windows.Forms.Label();
            label31.Text = "Địa điểm";
            label31.AutoSize = true;
            label31.Dock = System.Windows.Forms.DockStyle.Fill;
            label31.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label31.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label31, 0, 1);
            fields28.Controls.Add(txtDTQDiaDiem, 1, 1);
            var label32 = new System.Windows.Forms.Label();
            label32.Text = "Nội dung";
            label32.AutoSize = true;
            label32.Dock = System.Windows.Forms.DockStyle.Fill;
            label32.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label32.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label32, 2, 1);
            fields28.Controls.Add(txtDTQNoiDung, 3, 1);
            var label33 = new System.Windows.Forms.Label();
            label33.Text = "Ý nghĩa";
            label33.AutoSize = true;
            label33.Dock = System.Windows.Forms.DockStyle.Fill;
            label33.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label33.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label33, 0, 2);
            fields28.Controls.Add(txtDTQYNghia, 1, 2);
            layout27.Controls.Add(fields28);
            var actions34 = new System.Windows.Forms.FlowLayoutPanel();
            actions34.Dock = System.Windows.Forms.DockStyle.Top;
            actions34.AutoSize = true;
            actions34.Controls.Add(btnThemDTQ);
            layout27.Controls.Add(actions34);
            layout27.Controls.Add(dgvDTQ);
            var actions35 = new System.Windows.Forms.FlowLayoutPanel();
            actions35.Dock = System.Windows.Forms.DockStyle.Top;
            actions35.AutoSize = true;
            actions35.Controls.Add(btnDong);
            layout2.Controls.Add(actions35);
            this.btnThemPT.Click += this.btnThemPT_Click;
            this.btnThemDB.Click += this.btnThemDB_Click;
            this.btnThemHDV.Click += this.btnThemHDV_Click;
            this.btnThemDTQ.Click += this.btnThemDTQ_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmDanhMuc_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Danh mục";
            this.Name = "FrmDanhMuc";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.TabControl tabDanhMuc;
        private System.Windows.Forms.DataGridView dgvPT;
        private System.Windows.Forms.TextBox txtPTMa;
        private System.Windows.Forms.TextBox txtPTTen;
        private System.Windows.Forms.TextBox txtPTGhiChu;
        private System.Windows.Forms.Button btnThemPT;
        private System.Windows.Forms.DataGridView dgvDB;
        private System.Windows.Forms.TextBox txtDBMa;
        private System.Windows.Forms.TextBox txtDBTen;
        private System.Windows.Forms.TextBox txtDBDiaChi;
        private System.Windows.Forms.TextBox txtDBDT;
        private System.Windows.Forms.Button btnThemDB;
        private System.Windows.Forms.DataGridView dgvHDV;
        private System.Windows.Forms.TextBox txtHDVMa;
        private System.Windows.Forms.TextBox txtHDVTen;
        private System.Windows.Forms.TextBox txtHDVDT;
        private System.Windows.Forms.NumericUpDown numLuong;
        private System.Windows.Forms.Button btnThemHDV;
        private System.Windows.Forms.DataGridView dgvDTQ;
        private System.Windows.Forms.TextBox txtDTQMa;
        private System.Windows.Forms.TextBox txtDTQTen;
        private System.Windows.Forms.TextBox txtDTQDiaDiem;
        private System.Windows.Forms.TextBox txtDTQNoiDung;
        private System.Windows.Forms.TextBox txtDTQYNghia;
        private System.Windows.Forms.Button btnThemDTQ;
        private System.Windows.Forms.Button btnDong;
    }
}
