namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.txtSo = new System.Windows.Forms.TextBox();
            txtSo.Name = "txtSo";
            txtSo.Dock = System.Windows.Forms.DockStyle.Fill;
            txtSo.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.cboChuyen = new System.Windows.Forms.ComboBox();
            cboChuyen.Name = "cboChuyen";
            cboChuyen.Dock = System.Windows.Forms.DockStyle.Fill;
            cboChuyen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboChuyen.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDiemBan = new System.Windows.Forms.ComboBox();
            cboDiemBan.Name = "cboDiemBan";
            cboDiemBan.Dock = System.Windows.Forms.DockStyle.Fill;
            cboDiemBan.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboDiemBan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtTen = new System.Windows.Forms.TextBox();
            txtTen.Name = "txtTen";
            txtTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtDT = new System.Windows.Forms.TextBox();
            txtDT.Name = "txtDT";
            txtDT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.numNguoi = new System.Windows.Forms.NumericUpDown();
            numNguoi.Name = "numNguoi";
            numNguoi.Dock = System.Windows.Forms.DockStyle.Fill;
            numNguoi.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numNguoi.Maximum = 11M;
            numNguoi.Minimum = 1M;
            numNguoi.Value = 1M;
            this.lblThanhTien = new System.Windows.Forms.Label();
            lblThanhTien.Name = "lblThanhTien";
            lblThanhTien.Dock = System.Windows.Forms.DockStyle.Fill;
            lblThanhTien.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            lblThanhTien.Text = "-";
            lblThanhTien.AutoSize = true;
            this.btnDangKy = new System.Windows.Forms.Button();
            btnDangKy.Name = "btnDangKy";
            btnDangKy.Text = "Đăng ký và thanh toán vé";
            btnDangKy.AutoSize = true;
            btnDangKy.MinimumSize = new System.Drawing.Size(145, 34);
            btnDangKy.Margin = new System.Windows.Forms.Padding(4);
            this.dgv = new System.Windows.Forms.DataGridView();
            dgv.Name = "dgv";
            dgv.Dock = System.Windows.Forms.DockStyle.Top;
            dgv.Height = 185;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.AutoGenerateColumns = true;
            dgv.MultiSelect = false;
            dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.BackgroundColor = System.Drawing.Color.White;
            dgv.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            var fields3 = new System.Windows.Forms.TableLayoutPanel();
            fields3.Dock = System.Windows.Forms.DockStyle.Top;
            fields3.AutoSize = true;
            fields3.ColumnCount = 4;
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label4 = new System.Windows.Forms.Label();
            label4.Text = "Số đăng ký";
            label4.AutoSize = true;
            label4.Dock = System.Windows.Forms.DockStyle.Fill;
            label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label4.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label4, 0, 0);
            fields3.Controls.Add(txtSo, 1, 0);
            var label5 = new System.Windows.Forms.Label();
            label5.Text = "Chuyến";
            label5.AutoSize = true;
            label5.Dock = System.Windows.Forms.DockStyle.Fill;
            label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label5.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label5, 2, 0);
            fields3.Controls.Add(cboChuyen, 3, 0);
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Điểm bán vé";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label6, 0, 1);
            fields3.Controls.Add(cboDiemBan, 1, 1);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Người đăng ký";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label7, 2, 1);
            fields3.Controls.Add(txtTen, 3, 1);
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Điện thoại";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label8, 0, 2);
            fields3.Controls.Add(txtDT, 1, 2);
            var label9 = new System.Windows.Forms.Label();
            label9.Text = "Số người";
            label9.AutoSize = true;
            label9.Dock = System.Windows.Forms.DockStyle.Fill;
            label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label9.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label9, 2, 2);
            fields3.Controls.Add(numNguoi, 3, 2);
            var label10 = new System.Windows.Forms.Label();
            label10.Text = "Thành tiền";
            label10.AutoSize = true;
            label10.Dock = System.Windows.Forms.DockStyle.Fill;
            label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label10.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label10, 0, 3);
            fields3.Controls.Add(lblThanhTien, 1, 3);
            layout2.Controls.Add(fields3);
            var actions11 = new System.Windows.Forms.FlowLayoutPanel();
            actions11.Dock = System.Windows.Forms.DockStyle.Top;
            actions11.AutoSize = true;
            actions11.Controls.Add(btnDangKy);
            actions11.Controls.Add(btnDong);
            layout2.Controls.Add(actions11);
            layout2.Controls.Add(dgv);
            this.cboChuyen.SelectedIndexChanged += this.TinhTien;
            this.numNguoi.ValueChanged += this.TinhTien;
            this.btnDangKy.Click += this.btnDangKy_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmDangKyLe_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Đăng ký khách lẻ";
            this.Name = "FrmDangKyLe";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.TextBox txtSo;
        private System.Windows.Forms.ComboBox cboChuyen;
        private System.Windows.Forms.ComboBox cboDiemBan;
        private System.Windows.Forms.TextBox txtTen;
        private System.Windows.Forms.TextBox txtDT;
        private System.Windows.Forms.NumericUpDown numNguoi;
        private System.Windows.Forms.Label lblThanhTien;
        private System.Windows.Forms.Button btnDangKy;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Button btnDong;
    }
}
