namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabKT = new System.Windows.Forms.TabControl();
            tabKT.Name = "tabKT";
            tabKT.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDoan = new System.Windows.Forms.DataGridView();
            dgvDoan.Name = "dgvDoan";
            dgvDoan.Dock = System.Windows.Forms.DockStyle.Top;
            dgvDoan.Height = 185;
            dgvDoan.ReadOnly = true;
            dgvDoan.AllowUserToAddRows = false;
            dgvDoan.AllowUserToDeleteRows = false;
            dgvDoan.AutoGenerateColumns = true;
            dgvDoan.MultiSelect = false;
            dgvDoan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvDoan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvDoan.BackgroundColor = System.Drawing.Color.White;
            dgvDoan.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtSoTT = new System.Windows.Forms.TextBox();
            txtSoTT.Name = "txtSoTT";
            txtSoTT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtSoTT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtSoDK = new System.Windows.Forms.TextBox();
            txtSoDK.Name = "txtSoDK";
            txtSoDK.Dock = System.Windows.Forms.DockStyle.Fill;
            txtSoDK.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            txtSoDK.ReadOnly = true;
            this.dtTT = new System.Windows.Forms.DateTimePicker();
            dtTT.Name = "dtTT";
            dtTT.Dock = System.Windows.Forms.DockStyle.Fill;
            dtTT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtTT.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtTT.CustomFormat = "dd/MM/yyyy";
            this.numTien = new System.Windows.Forms.NumericUpDown();
            numTien.Name = "numTien";
            numTien.Dock = System.Windows.Forms.DockStyle.Fill;
            numTien.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numTien.Maximum = 1000000000000M;
            numTien.Minimum = 0M;
            numTien.Value = 0M;
            numTien.DecimalPlaces = 2;
            numTien.ThousandsSeparator = true;
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            txtGhiChu.Name = "txtGhiChu";
            txtGhiChu.Dock = System.Windows.Forms.DockStyle.Fill;
            txtGhiChu.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThanhToan = new System.Windows.Forms.Button();
            btnThanhToan.Name = "btnThanhToan";
            btnThanhToan.Text = "Ghi nhận thanh toán";
            btnThanhToan.AutoSize = true;
            btnThanhToan.MinimumSize = new System.Drawing.Size(145, 34);
            btnThanhToan.Margin = new System.Windows.Forms.Padding(4);
            this.cboLoaiKS = new System.Windows.Forms.ComboBox();
            cboLoaiKS.Name = "cboLoaiKS";
            cboLoaiKS.Dock = System.Windows.Forms.DockStyle.Fill;
            cboLoaiKS.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboLoaiKS.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDangKy = new System.Windows.Forms.ComboBox();
            cboDangKy.Name = "cboDangKy";
            cboDangKy.Dock = System.Windows.Forms.DockStyle.Fill;
            cboDangKy.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboDangKy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtMaKS = new System.Windows.Forms.TextBox();
            txtMaKS.Name = "txtMaKS";
            txtMaKS.Dock = System.Windows.Forms.DockStyle.Fill;
            txtMaKS.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.dtGui = new System.Windows.Forms.DateTimePicker();
            dtGui.Name = "dtGui";
            dtGui.Dock = System.Windows.Forms.DockStyle.Fill;
            dtGui.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtGui.CustomFormat = "dd/MM/yyyy";
            this.btnGui = new System.Windows.Forms.Button();
            btnGui.Name = "btnGui";
            btnGui.Text = "Gửi phiếu khảo sát";
            btnGui.AutoSize = true;
            btnGui.MinimumSize = new System.Drawing.Size(145, 34);
            btnGui.Margin = new System.Windows.Forms.Padding(4);
            this.dgvKS = new System.Windows.Forms.DataGridView();
            dgvKS.Name = "dgvKS";
            dgvKS.Dock = System.Windows.Forms.DockStyle.Top;
            dgvKS.Height = 185;
            dgvKS.ReadOnly = true;
            dgvKS.AllowUserToAddRows = false;
            dgvKS.AllowUserToDeleteRows = false;
            dgvKS.AutoGenerateColumns = true;
            dgvKS.MultiSelect = false;
            dgvKS.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvKS.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvKS.BackgroundColor = System.Drawing.Color.White;
            dgvKS.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtKSChon = new System.Windows.Forms.TextBox();
            txtKSChon.Name = "txtKSChon";
            txtKSChon.Dock = System.Windows.Forms.DockStyle.Fill;
            txtKSChon.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            txtKSChon.ReadOnly = true;
            this.dtPH = new System.Windows.Forms.DateTimePicker();
            dtPH.Name = "dtPH";
            dtPH.Dock = System.Windows.Forms.DockStyle.Fill;
            dtPH.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtPH.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtPH.CustomFormat = "dd/MM/yyyy";
            this.numDiem = new System.Windows.Forms.NumericUpDown();
            numDiem.Name = "numDiem";
            numDiem.Dock = System.Windows.Forms.DockStyle.Fill;
            numDiem.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numDiem.Maximum = 5M;
            numDiem.Minimum = 1M;
            numDiem.Value = 1M;
            this.txtGopY = new System.Windows.Forms.TextBox();
            txtGopY.Name = "txtGopY";
            txtGopY.Dock = System.Windows.Forms.DockStyle.Fill;
            txtGopY.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnGhiPH = new System.Windows.Forms.Button();
            btnGhiPH.Name = "btnGhiPH";
            btnGhiPH.Text = "Ghi nhận góp ý";
            btnGhiPH.AutoSize = true;
            btnGhiPH.MinimumSize = new System.Drawing.Size(145, 34);
            btnGhiPH.Margin = new System.Windows.Forms.Padding(4);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            tabKT.Dock = System.Windows.Forms.DockStyle.Top;
            tabKT.Height = 610;
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            layout2.Controls.Add(tabKT);
            var page3 = new System.Windows.Forms.TabPage();
            page3.Text = "Thanh toán sau tour (đoàn)";
            page3.AutoScroll = true;
            tabKT.Controls.Add(page3);
            var layout4 = new System.Windows.Forms.TableLayoutPanel();
            layout4.Dock = System.Windows.Forms.DockStyle.Top;
            layout4.AutoSize = true;
            layout4.ColumnCount = 1;
            layout4.Padding = new System.Windows.Forms.Padding(12);
            layout4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page3.Controls.Add(layout4);
            var fields5 = new System.Windows.Forms.TableLayoutPanel();
            fields5.Dock = System.Windows.Forms.DockStyle.Top;
            fields5.AutoSize = true;
            fields5.ColumnCount = 4;
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Số thanh toán";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label6, 0, 0);
            fields5.Controls.Add(txtSoTT, 1, 0);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Phiếu đoàn";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label7, 2, 0);
            fields5.Controls.Add(txtSoDK, 3, 0);
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Ngày thanh toán";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label8, 0, 1);
            fields5.Controls.Add(dtTT, 1, 1);
            var label9 = new System.Windows.Forms.Label();
            label9.Text = "Số tiền";
            label9.AutoSize = true;
            label9.Dock = System.Windows.Forms.DockStyle.Fill;
            label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label9.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label9, 2, 1);
            fields5.Controls.Add(numTien, 3, 1);
            var label10 = new System.Windows.Forms.Label();
            label10.Text = "Ghi chú";
            label10.AutoSize = true;
            label10.Dock = System.Windows.Forms.DockStyle.Fill;
            label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label10.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label10, 0, 2);
            fields5.Controls.Add(txtGhiChu, 1, 2);
            layout4.Controls.Add(fields5);
            var actions11 = new System.Windows.Forms.FlowLayoutPanel();
            actions11.Dock = System.Windows.Forms.DockStyle.Top;
            actions11.AutoSize = true;
            actions11.Controls.Add(btnThanhToan);
            layout4.Controls.Add(actions11);
            layout4.Controls.Add(dgvDoan);
            var page12 = new System.Windows.Forms.TabPage();
            page12.Text = "Khảo sát khách hàng";
            page12.AutoScroll = true;
            tabKT.Controls.Add(page12);
            var layout13 = new System.Windows.Forms.TableLayoutPanel();
            layout13.Dock = System.Windows.Forms.DockStyle.Top;
            layout13.AutoSize = true;
            layout13.ColumnCount = 1;
            layout13.Padding = new System.Windows.Forms.Padding(12);
            layout13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page12.Controls.Add(layout13);
            var fields14 = new System.Windows.Forms.TableLayoutPanel();
            fields14.Dock = System.Windows.Forms.DockStyle.Top;
            fields14.AutoSize = true;
            fields14.ColumnCount = 4;
            fields14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label15 = new System.Windows.Forms.Label();
            label15.Text = "Loại khách";
            label15.AutoSize = true;
            label15.Dock = System.Windows.Forms.DockStyle.Fill;
            label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label15.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label15, 0, 0);
            fields14.Controls.Add(cboLoaiKS, 1, 0);
            var label16 = new System.Windows.Forms.Label();
            label16.Text = "Đăng ký đã kết thúc";
            label16.AutoSize = true;
            label16.Dock = System.Windows.Forms.DockStyle.Fill;
            label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label16.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label16, 2, 0);
            fields14.Controls.Add(cboDangKy, 3, 0);
            var label17 = new System.Windows.Forms.Label();
            label17.Text = "Mã KS";
            label17.AutoSize = true;
            label17.Dock = System.Windows.Forms.DockStyle.Fill;
            label17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label17.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label17, 0, 1);
            fields14.Controls.Add(txtMaKS, 1, 1);
            var label18 = new System.Windows.Forms.Label();
            label18.Text = "Ngày gửi";
            label18.AutoSize = true;
            label18.Dock = System.Windows.Forms.DockStyle.Fill;
            label18.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label18.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label18, 2, 1);
            fields14.Controls.Add(dtGui, 3, 1);
            var label19 = new System.Windows.Forms.Label();
            label19.Text = "Phiếu chọn";
            label19.AutoSize = true;
            label19.Dock = System.Windows.Forms.DockStyle.Fill;
            label19.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label19.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label19, 0, 2);
            fields14.Controls.Add(txtKSChon, 1, 2);
            var label20 = new System.Windows.Forms.Label();
            label20.Text = "Ngày phản hồi";
            label20.AutoSize = true;
            label20.Dock = System.Windows.Forms.DockStyle.Fill;
            label20.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label20.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label20, 2, 2);
            fields14.Controls.Add(dtPH, 3, 2);
            var label21 = new System.Windows.Forms.Label();
            label21.Text = "Điểm (1-5)";
            label21.AutoSize = true;
            label21.Dock = System.Windows.Forms.DockStyle.Fill;
            label21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label21.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label21, 0, 3);
            fields14.Controls.Add(numDiem, 1, 3);
            var label22 = new System.Windows.Forms.Label();
            label22.Text = "Góp ý";
            label22.AutoSize = true;
            label22.Dock = System.Windows.Forms.DockStyle.Fill;
            label22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label22.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields14.Controls.Add(label22, 2, 3);
            fields14.Controls.Add(txtGopY, 3, 3);
            layout13.Controls.Add(fields14);
            var actions23 = new System.Windows.Forms.FlowLayoutPanel();
            actions23.Dock = System.Windows.Forms.DockStyle.Top;
            actions23.AutoSize = true;
            actions23.Controls.Add(btnGui);
            actions23.Controls.Add(btnGhiPH);
            layout13.Controls.Add(actions23);
            layout13.Controls.Add(dgvKS);
            var actions24 = new System.Windows.Forms.FlowLayoutPanel();
            actions24.Dock = System.Windows.Forms.DockStyle.Top;
            actions24.AutoSize = true;
            actions24.Controls.Add(btnDong);
            layout2.Controls.Add(actions24);
            this.dgvDoan.SelectionChanged += this.dgvDoan_SelectionChanged;
            this.btnThanhToan.Click += this.btnThanhToan_Click;
            this.cboLoaiKS.SelectedIndexChanged += this.cboLoaiKS_SelectedIndexChanged;
            this.btnGui.Click += this.btnGui_Click;
            this.dgvKS.SelectionChanged += this.dgvKS_SelectionChanged;
            this.btnGhiPH.Click += this.btnGhiPH_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmKetThucKhaoSat_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Kết thúc tour và khảo sát";
            this.Name = "FrmKetThucKhaoSat";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.TabControl tabKT;
        private System.Windows.Forms.DataGridView dgvDoan;
        private System.Windows.Forms.TextBox txtSoTT;
        private System.Windows.Forms.TextBox txtSoDK;
        private System.Windows.Forms.DateTimePicker dtTT;
        private System.Windows.Forms.NumericUpDown numTien;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.ComboBox cboLoaiKS;
        private System.Windows.Forms.ComboBox cboDangKy;
        private System.Windows.Forms.TextBox txtMaKS;
        private System.Windows.Forms.DateTimePicker dtGui;
        private System.Windows.Forms.Button btnGui;
        private System.Windows.Forms.DataGridView dgvKS;
        private System.Windows.Forms.TextBox txtKSChon;
        private System.Windows.Forms.DateTimePicker dtPH;
        private System.Windows.Forms.NumericUpDown numDiem;
        private System.Windows.Forms.TextBox txtGopY;
        private System.Windows.Forms.Button btnGhiPH;
        private System.Windows.Forms.Button btnDong;
    }
}
