namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmLuongThongKe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabTK = new System.Windows.Forms.TabControl();
            tabTK.Name = "tabTK";
            tabTK.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numThang = new System.Windows.Forms.NumericUpDown();
            numThang.Name = "numThang";
            numThang.Dock = System.Windows.Forms.DockStyle.Fill;
            numThang.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numThang.Maximum = 12M;
            numThang.Minimum = 1M;
            numThang.Value = 1M;
            this.numNam = new System.Windows.Forms.NumericUpDown();
            numNam.Name = "numNam";
            numNam.Dock = System.Windows.Forms.DockStyle.Fill;
            numNam.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numNam.Maximum = 2100M;
            numNam.Minimum = 2000M;
            numNam.Value = 2026M;
            this.btnLuong = new System.Windows.Forms.Button();
            btnLuong.Name = "btnLuong";
            btnLuong.Text = "Tính lương";
            btnLuong.AutoSize = true;
            btnLuong.MinimumSize = new System.Drawing.Size(145, 34);
            btnLuong.Margin = new System.Windows.Forms.Padding(4);
            this.dgvLuong = new System.Windows.Forms.DataGridView();
            dgvLuong.Name = "dgvLuong";
            dgvLuong.Dock = System.Windows.Forms.DockStyle.Top;
            dgvLuong.Height = 185;
            dgvLuong.ReadOnly = true;
            dgvLuong.AllowUserToAddRows = false;
            dgvLuong.AllowUserToDeleteRows = false;
            dgvLuong.AutoGenerateColumns = true;
            dgvLuong.MultiSelect = false;
            dgvLuong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvLuong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvLuong.BackgroundColor = System.Drawing.Color.White;
            dgvLuong.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.dtTu = new System.Windows.Forms.DateTimePicker();
            dtTu.Name = "dtTu";
            dtTu.Dock = System.Windows.Forms.DockStyle.Fill;
            dtTu.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtTu.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtTu.CustomFormat = "dd/MM/yyyy";
            this.dtDen = new System.Windows.Forms.DateTimePicker();
            dtDen.Name = "dtDen";
            dtDen.Dock = System.Windows.Forms.DockStyle.Fill;
            dtDen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            dtDen.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtDen.CustomFormat = "dd/MM/yyyy";
            this.btnTongHop = new System.Windows.Forms.Button();
            btnTongHop.Name = "btnTongHop";
            btnTongHop.Text = "Thống kê";
            btnTongHop.AutoSize = true;
            btnTongHop.MinimumSize = new System.Drawing.Size(145, 34);
            btnTongHop.Margin = new System.Windows.Forms.Padding(4);
            this.dgvTongHop = new System.Windows.Forms.DataGridView();
            dgvTongHop.Name = "dgvTongHop";
            dgvTongHop.Dock = System.Windows.Forms.DockStyle.Top;
            dgvTongHop.Height = 185;
            dgvTongHop.ReadOnly = true;
            dgvTongHop.AllowUserToAddRows = false;
            dgvTongHop.AllowUserToDeleteRows = false;
            dgvTongHop.AutoGenerateColumns = true;
            dgvTongHop.MultiSelect = false;
            dgvTongHop.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvTongHop.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvTongHop.BackgroundColor = System.Drawing.Color.White;
            dgvTongHop.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            tabTK.Dock = System.Windows.Forms.DockStyle.Top;
            tabTK.Height = 610;
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            layout2.Controls.Add(tabTK);
            var page3 = new System.Windows.Forms.TabPage();
            page3.Text = "Lương hướng dẫn viên";
            page3.AutoScroll = true;
            tabTK.Controls.Add(page3);
            var layout4 = new System.Windows.Forms.TableLayoutPanel();
            layout4.Dock = System.Windows.Forms.DockStyle.Top;
            layout4.AutoSize = true;
            layout4.ColumnCount = 1;
            layout4.Padding = new System.Windows.Forms.Padding(12);
            layout4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page3.Controls.Add(layout4);
            var fields5 = new System.Windows.Forms.TableLayoutPanel();
            fields5.Dock = System.Windows.Forms.DockStyle.Top;
            fields5.AutoSize = true;
            fields5.ColumnCount = 4;
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label6 = new System.Windows.Forms.Label();
            label6.Text = "Tháng";
            label6.AutoSize = true;
            label6.Dock = System.Windows.Forms.DockStyle.Fill;
            label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label6.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label6, 0, 0);
            fields5.Controls.Add(numThang, 1, 0);
            var label7 = new System.Windows.Forms.Label();
            label7.Text = "Năm";
            label7.AutoSize = true;
            label7.Dock = System.Windows.Forms.DockStyle.Fill;
            label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label7.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields5.Controls.Add(label7, 2, 0);
            fields5.Controls.Add(numNam, 3, 0);
            layout4.Controls.Add(fields5);
            var actions8 = new System.Windows.Forms.FlowLayoutPanel();
            actions8.Dock = System.Windows.Forms.DockStyle.Top;
            actions8.AutoSize = true;
            actions8.Controls.Add(btnLuong);
            layout4.Controls.Add(actions8);
            layout4.Controls.Add(dgvLuong);
            var page9 = new System.Windows.Forms.TabPage();
            page9.Text = "Thống kê tổng hợp";
            page9.AutoScroll = true;
            tabTK.Controls.Add(page9);
            var layout10 = new System.Windows.Forms.TableLayoutPanel();
            layout10.Dock = System.Windows.Forms.DockStyle.Top;
            layout10.AutoSize = true;
            layout10.ColumnCount = 1;
            layout10.Padding = new System.Windows.Forms.Padding(12);
            layout10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page9.Controls.Add(layout10);
            var fields11 = new System.Windows.Forms.TableLayoutPanel();
            fields11.Dock = System.Windows.Forms.DockStyle.Top;
            fields11.AutoSize = true;
            fields11.ColumnCount = 4;
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label12 = new System.Windows.Forms.Label();
            label12.Text = "Từ ngày";
            label12.AutoSize = true;
            label12.Dock = System.Windows.Forms.DockStyle.Fill;
            label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label12.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label12, 0, 0);
            fields11.Controls.Add(dtTu, 1, 0);
            var label13 = new System.Windows.Forms.Label();
            label13.Text = "Đến ngày";
            label13.AutoSize = true;
            label13.Dock = System.Windows.Forms.DockStyle.Fill;
            label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label13.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields11.Controls.Add(label13, 2, 0);
            fields11.Controls.Add(dtDen, 3, 0);
            layout10.Controls.Add(fields11);
            var actions14 = new System.Windows.Forms.FlowLayoutPanel();
            actions14.Dock = System.Windows.Forms.DockStyle.Top;
            actions14.AutoSize = true;
            actions14.Controls.Add(btnTongHop);
            layout10.Controls.Add(actions14);
            layout10.Controls.Add(dgvTongHop);
            var actions15 = new System.Windows.Forms.FlowLayoutPanel();
            actions15.Dock = System.Windows.Forms.DockStyle.Top;
            actions15.AutoSize = true;
            actions15.Controls.Add(btnDong);
            layout2.Controls.Add(actions15);
            this.btnLuong.Click += this.btnLuong_Click;
            this.btnTongHop.Click += this.btnTongHop_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmLuongThongKe_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Lương và thống kê";
            this.Name = "FrmLuongThongKe";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.TabControl tabTK;
        private System.Windows.Forms.NumericUpDown numThang;
        private System.Windows.Forms.NumericUpDown numNam;
        private System.Windows.Forms.Button btnLuong;
        private System.Windows.Forms.DataGridView dgvLuong;
        private System.Windows.Forms.DateTimePicker dtTu;
        private System.Windows.Forms.DateTimePicker dtDen;
        private System.Windows.Forms.Button btnTongHop;
        private System.Windows.Forms.DataGridView dgvTongHop;
        private System.Windows.Forms.Button btnDong;
    }
}
