namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmMain
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.btnDanhMuc = new System.Windows.Forms.Button();
            btnDanhMuc.Name = "btnDanhMuc";
            btnDanhMuc.Text = "Danh mục";
            btnDanhMuc.AutoSize = true;
            btnDanhMuc.MinimumSize = new System.Drawing.Size(145, 34);
            btnDanhMuc.Margin = new System.Windows.Forms.Padding(4);
            this.btnTour = new System.Windows.Forms.Button();
            btnTour.Name = "btnTour";
            btnTour.Text = "Tour - hành trình";
            btnTour.AutoSize = true;
            btnTour.MinimumSize = new System.Drawing.Size(145, 34);
            btnTour.Margin = new System.Windows.Forms.Padding(4);
            this.btnChuyenLe = new System.Windows.Forms.Button();
            btnChuyenLe.Name = "btnChuyenLe";
            btnChuyenLe.Text = "Lịch chuyến khách lẻ";
            btnChuyenLe.AutoSize = true;
            btnChuyenLe.MinimumSize = new System.Drawing.Size(145, 34);
            btnChuyenLe.Margin = new System.Windows.Forms.Padding(4);
            this.btnDangKyLe = new System.Windows.Forms.Button();
            btnDangKyLe.Name = "btnDangKyLe";
            btnDangKyLe.Text = "Đăng ký khách lẻ";
            btnDangKyLe.AutoSize = true;
            btnDangKyLe.MinimumSize = new System.Drawing.Size(145, 34);
            btnDangKyLe.Margin = new System.Windows.Forms.Padding(4);
            this.btnDangKyDoan = new System.Windows.Forms.Button();
            btnDangKyDoan.Name = "btnDangKyDoan";
            btnDangKyDoan.Text = "Đăng ký theo đoàn";
            btnDangKyDoan.AutoSize = true;
            btnDangKyDoan.MinimumSize = new System.Drawing.Size(145, 34);
            btnDangKyDoan.Margin = new System.Windows.Forms.Padding(4);
            this.btnPhanCong = new System.Windows.Forms.Button();
            btnPhanCong.Name = "btnPhanCong";
            btnPhanCong.Text = "Phân công hướng dẫn viên";
            btnPhanCong.AutoSize = true;
            btnPhanCong.MinimumSize = new System.Drawing.Size(145, 34);
            btnPhanCong.Margin = new System.Windows.Forms.Padding(4);
            this.btnKetThuc = new System.Windows.Forms.Button();
            btnKetThuc.Name = "btnKetThuc";
            btnKetThuc.Text = "Kết thúc tour - khảo sát";
            btnKetThuc.AutoSize = true;
            btnKetThuc.MinimumSize = new System.Drawing.Size(145, 34);
            btnKetThuc.Margin = new System.Windows.Forms.Padding(4);
            this.btnThongKe = new System.Windows.Forms.Button();
            btnThongKe.Name = "btnThongKe";
            btnThongKe.Text = "Lương - thống kê";
            btnThongKe.AutoSize = true;
            btnThongKe.MinimumSize = new System.Drawing.Size(145, 34);
            btnThongKe.Margin = new System.Windows.Forms.Padding(4);
            this.btnThoat = new System.Windows.Forms.Button();
            btnThoat.Name = "btnThoat";
            btnThoat.Text = "Thoát";
            btnThoat.AutoSize = true;
            btnThoat.MinimumSize = new System.Drawing.Size(145, 34);
            btnThoat.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var layout1 = new System.Windows.Forms.TableLayoutPanel();
            layout1.Dock = System.Windows.Forms.DockStyle.Top;
            layout1.AutoSize = true;
            layout1.ColumnCount = 1;
            layout1.Padding = new System.Windows.Forms.Padding(12);
            layout1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.Controls.Add(layout1);
            var title2 = new System.Windows.Forms.Label();
            title2.Text = "CÔNG TY DU LỊCH VĂN HÓA VIỆT";
            title2.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            title2.AutoSize = true;
            title2.Margin = new System.Windows.Forms.Padding(10, 20, 10, 20);
            layout1.Controls.Add(title2);
            var menu3 = new System.Windows.Forms.FlowLayoutPanel();
            menu3.Dock = System.Windows.Forms.DockStyle.Top;
            menu3.AutoSize = true;
            menu3.MaximumSize = new System.Drawing.Size(900, 0);
            btnDanhMuc.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnDanhMuc);
            btnTour.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnTour);
            btnChuyenLe.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnChuyenLe);
            btnDangKyLe.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnDangKyLe);
            btnDangKyDoan.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnDangKyDoan);
            btnPhanCong.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnPhanCong);
            btnKetThuc.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnKetThuc);
            btnThongKe.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnThongKe);
            btnThoat.MinimumSize = new System.Drawing.Size(270, 65);
            menu3.Controls.Add(btnThoat);
            layout1.Controls.Add(menu3);
            var hint4 = new System.Windows.Forms.Label();
            hint4.AutoSize = true;
            hint4.Text = "Ctrl + Shift + S: lưu ảnh Form hiện tại vào thư mục Evidence";
            hint4.Padding = new System.Windows.Forms.Padding(10, 20, 0, 0);
            layout1.Controls.Add(hint4);
            this.btnDanhMuc.Click += this.btnDanhMuc_Click;
            this.btnTour.Click += this.btnTour_Click;
            this.btnChuyenLe.Click += this.btnChuyenLe_Click;
            this.btnDangKyLe.Click += this.btnDangKyLe_Click;
            this.btnDangKyDoan.Click += this.btnDangKyDoan_Click;
            this.btnPhanCong.Click += this.btnPhanCong_Click;
            this.btnKetThuc.Click += this.btnKetThuc_Click;
            this.btnThongKe.Click += this.btnThongKe_Click;
            this.btnThoat.Click += this.btnThoat_Click;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Công ty du lịch Văn Hóa Việt";
            this.Name = "FrmMain";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.Button btnDanhMuc;
        private System.Windows.Forms.Button btnTour;
        private System.Windows.Forms.Button btnChuyenLe;
        private System.Windows.Forms.Button btnDangKyLe;
        private System.Windows.Forms.Button btnDangKyDoan;
        private System.Windows.Forms.Button btnPhanCong;
        private System.Windows.Forms.Button btnKetThuc;
        private System.Windows.Forms.Button btnThongKe;
        private System.Windows.Forms.Button btnThoat;
    }
}
