namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.cboTour = new System.Windows.Forms.ComboBox();
            cboTour.Name = "cboTour";
            cboTour.Dock = System.Windows.Forms.DockStyle.Fill;
            cboTour.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.tabTour = new System.Windows.Forms.TabControl();
            tabTour.Name = "tabTour";
            tabTour.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvTour = new System.Windows.Forms.DataGridView();
            dgvTour.Name = "dgvTour";
            dgvTour.Dock = System.Windows.Forms.DockStyle.Top;
            dgvTour.Height = 185;
            dgvTour.ReadOnly = true;
            dgvTour.AllowUserToAddRows = false;
            dgvTour.AllowUserToDeleteRows = false;
            dgvTour.AutoGenerateColumns = true;
            dgvTour.MultiSelect = false;
            dgvTour.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvTour.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvTour.BackgroundColor = System.Drawing.Color.White;
            dgvTour.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.txtMa = new System.Windows.Forms.TextBox();
            txtMa.Name = "txtMa";
            txtMa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtMa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.txtTen = new System.Windows.Forms.TextBox();
            txtTen.Name = "txtTen";
            txtTen.Dock = System.Windows.Forms.DockStyle.Fill;
            txtTen.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.numNgay = new System.Windows.Forms.NumericUpDown();
            numNgay.Name = "numNgay";
            numNgay.Dock = System.Windows.Forms.DockStyle.Fill;
            numNgay.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numNgay.Maximum = 365M;
            numNgay.Minimum = 1M;
            numNgay.Value = 1M;
            this.numDem = new System.Windows.Forms.NumericUpDown();
            numDem.Name = "numDem";
            numDem.Dock = System.Windows.Forms.DockStyle.Fill;
            numDem.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numDem.Maximum = 365M;
            numDem.Minimum = 0M;
            numDem.Value = 0M;
            this.numGia = new System.Windows.Forms.NumericUpDown();
            numGia.Name = "numGia";
            numGia.Dock = System.Windows.Forms.DockStyle.Fill;
            numGia.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numGia.Maximum = 1000000000000M;
            numGia.Minimum = 0M;
            numGia.Value = 0M;
            numGia.DecimalPlaces = 2;
            numGia.ThousandsSeparator = true;
            this.txtMoTa = new System.Windows.Forms.TextBox();
            txtMoTa.Name = "txtMoTa";
            txtMoTa.Dock = System.Windows.Forms.DockStyle.Fill;
            txtMoTa.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemTour = new System.Windows.Forms.Button();
            btnThemTour.Name = "btnThemTour";
            btnThemTour.Text = "Thêm tour";
            btnThemTour.AutoSize = true;
            btnThemTour.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemTour.Margin = new System.Windows.Forms.Padding(4);
            this.dgvDiemDung = new System.Windows.Forms.DataGridView();
            dgvDiemDung.Name = "dgvDiemDung";
            dgvDiemDung.Dock = System.Windows.Forms.DockStyle.Top;
            dgvDiemDung.Height = 185;
            dgvDiemDung.ReadOnly = true;
            dgvDiemDung.AllowUserToAddRows = false;
            dgvDiemDung.AllowUserToDeleteRows = false;
            dgvDiemDung.AutoGenerateColumns = true;
            dgvDiemDung.MultiSelect = false;
            dgvDiemDung.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvDiemDung.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvDiemDung.BackgroundColor = System.Drawing.Color.White;
            dgvDiemDung.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.numThuTu = new System.Windows.Forms.NumericUpDown();
            numThuTu.Name = "numThuTu";
            numThuTu.Dock = System.Windows.Forms.DockStyle.Fill;
            numThuTu.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numThuTu.Maximum = 1000M;
            numThuTu.Minimum = 1M;
            numThuTu.Value = 1M;
            this.txtDiemDung = new System.Windows.Forms.TextBox();
            txtDiemDung.Name = "txtDiemDung";
            txtDiemDung.Dock = System.Windows.Forms.DockStyle.Fill;
            txtDiemDung.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.chkDoiPT = new System.Windows.Forms.CheckBox();
            chkDoiPT.Name = "chkDoiPT";
            chkDoiPT.Dock = System.Windows.Forms.DockStyle.Fill;
            chkDoiPT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            chkDoiPT.Text = "Đổi phương tiện";
            chkDoiPT.AutoSize = true;
            this.chkAn = new System.Windows.Forms.CheckBox();
            chkAn.Name = "chkAn";
            chkAn.Dock = System.Windows.Forms.DockStyle.Fill;
            chkAn.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            chkAn.Text = "Có nơi ăn";
            chkAn.AutoSize = true;
            this.chkKS = new System.Windows.Forms.CheckBox();
            chkKS.Name = "chkKS";
            chkKS.Dock = System.Windows.Forms.DockStyle.Fill;
            chkKS.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            chkKS.Text = "Có khách sạn";
            chkKS.AutoSize = true;
            this.numSao = new System.Windows.Forms.NumericUpDown();
            numSao.Name = "numSao";
            numSao.Dock = System.Windows.Forms.DockStyle.Fill;
            numSao.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numSao.Maximum = 5M;
            numSao.Minimum = 2M;
            numSao.Value = 2M;
            numSao.Enabled = false;
            this.txtGhiChuDD = new System.Windows.Forms.TextBox();
            txtGhiChuDD.Name = "txtGhiChuDD";
            txtGhiChuDD.Dock = System.Windows.Forms.DockStyle.Fill;
            txtGhiChuDD.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemDD = new System.Windows.Forms.Button();
            btnThemDD.Name = "btnThemDD";
            btnThemDD.Text = "Thêm điểm dừng";
            btnThemDD.AutoSize = true;
            btnThemDD.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemDD.Margin = new System.Windows.Forms.Padding(4);
            this.dgvChang = new System.Windows.Forms.DataGridView();
            dgvChang.Name = "dgvChang";
            dgvChang.Dock = System.Windows.Forms.DockStyle.Top;
            dgvChang.Height = 185;
            dgvChang.ReadOnly = true;
            dgvChang.AllowUserToAddRows = false;
            dgvChang.AllowUserToDeleteRows = false;
            dgvChang.AutoGenerateColumns = true;
            dgvChang.MultiSelect = false;
            dgvChang.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvChang.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvChang.BackgroundColor = System.Drawing.Color.White;
            dgvChang.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.numChang = new System.Windows.Forms.NumericUpDown();
            numChang.Name = "numChang";
            numChang.Dock = System.Windows.Forms.DockStyle.Fill;
            numChang.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numChang.Maximum = 1000M;
            numChang.Minimum = 1M;
            numChang.Value = 1M;
            this.cboPT = new System.Windows.Forms.ComboBox();
            cboPT.Name = "cboPT";
            cboPT.Dock = System.Windows.Forms.DockStyle.Fill;
            cboPT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboPT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtGhiChuPT = new System.Windows.Forms.TextBox();
            txtGhiChuPT.Name = "txtGhiChuPT";
            txtGhiChuPT.Dock = System.Windows.Forms.DockStyle.Fill;
            txtGhiChuPT.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            this.btnThemChang = new System.Windows.Forms.Button();
            btnThemChang.Name = "btnThemChang";
            btnThemChang.Text = "Gắn phương tiện";
            btnThemChang.AutoSize = true;
            btnThemChang.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemChang.Margin = new System.Windows.Forms.Padding(4);
            this.dgvTQ = new System.Windows.Forms.DataGridView();
            dgvTQ.Name = "dgvTQ";
            dgvTQ.Dock = System.Windows.Forms.DockStyle.Top;
            dgvTQ.Height = 185;
            dgvTQ.ReadOnly = true;
            dgvTQ.AllowUserToAddRows = false;
            dgvTQ.AllowUserToDeleteRows = false;
            dgvTQ.AutoGenerateColumns = true;
            dgvTQ.MultiSelect = false;
            dgvTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgvTQ.BackgroundColor = System.Drawing.Color.White;
            dgvTQ.Margin = new System.Windows.Forms.Padding(0, 8, 0, 10);
            this.cboDTQ = new System.Windows.Forms.ComboBox();
            cboDTQ.Name = "cboDTQ";
            cboDTQ.Dock = System.Windows.Forms.DockStyle.Fill;
            cboDTQ.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            cboDTQ.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.numThuTuTQ = new System.Windows.Forms.NumericUpDown();
            numThuTuTQ.Name = "numThuTuTQ";
            numThuTuTQ.Dock = System.Windows.Forms.DockStyle.Fill;
            numThuTuTQ.Margin = new System.Windows.Forms.Padding(4, 6, 10, 6);
            numThuTuTQ.Maximum = 1000M;
            numThuTuTQ.Minimum = 1M;
            numThuTuTQ.Value = 1M;
            this.btnThemTQ = new System.Windows.Forms.Button();
            btnThemTQ.Name = "btnThemTQ";
            btnThemTQ.Text = "Gắn điểm TQ";
            btnThemTQ.AutoSize = true;
            btnThemTQ.MinimumSize = new System.Drawing.Size(145, 34);
            btnThemTQ.Margin = new System.Windows.Forms.Padding(4);
            this.btnDong = new System.Windows.Forms.Button();
            btnDong.Name = "btnDong";
            btnDong.Text = "Đóng";
            btnDong.AutoSize = true;
            btnDong.MinimumSize = new System.Drawing.Size(145, 34);
            btnDong.Margin = new System.Windows.Forms.Padding(4);
            this.SuspendLayout();
            var scroll1 = new System.Windows.Forms.Panel();
            scroll1.Dock = System.Windows.Forms.DockStyle.Fill;
            scroll1.AutoScroll = true;
            this.Controls.Add(scroll1);
            tabTour.Dock = System.Windows.Forms.DockStyle.Top;
            tabTour.Height = 610;
            var layout2 = new System.Windows.Forms.TableLayoutPanel();
            layout2.Dock = System.Windows.Forms.DockStyle.Top;
            layout2.AutoSize = true;
            layout2.ColumnCount = 1;
            layout2.Padding = new System.Windows.Forms.Padding(12);
            layout2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            scroll1.Controls.Add(layout2);
            var fields3 = new System.Windows.Forms.TableLayoutPanel();
            fields3.Dock = System.Windows.Forms.DockStyle.Top;
            fields3.AutoSize = true;
            fields3.ColumnCount = 4;
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label4 = new System.Windows.Forms.Label();
            label4.Text = "Tour đang chọn (cho các tab hành trình)";
            label4.AutoSize = true;
            label4.Dock = System.Windows.Forms.DockStyle.Fill;
            label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label4.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields3.Controls.Add(label4, 0, 0);
            fields3.Controls.Add(cboTour, 1, 0);
            layout2.Controls.Add(fields3);
            layout2.Controls.Add(tabTour);
            var page5 = new System.Windows.Forms.TabPage();
            page5.Text = "Tour";
            page5.AutoScroll = true;
            tabTour.Controls.Add(page5);
            var layout6 = new System.Windows.Forms.TableLayoutPanel();
            layout6.Dock = System.Windows.Forms.DockStyle.Top;
            layout6.AutoSize = true;
            layout6.ColumnCount = 1;
            layout6.Padding = new System.Windows.Forms.Padding(12);
            layout6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page5.Controls.Add(layout6);
            var fields7 = new System.Windows.Forms.TableLayoutPanel();
            fields7.Dock = System.Windows.Forms.DockStyle.Top;
            fields7.AutoSize = true;
            fields7.ColumnCount = 4;
            fields7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label8 = new System.Windows.Forms.Label();
            label8.Text = "Mã tour";
            label8.AutoSize = true;
            label8.Dock = System.Windows.Forms.DockStyle.Fill;
            label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label8.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label8, 0, 0);
            fields7.Controls.Add(txtMa, 1, 0);
            var label9 = new System.Windows.Forms.Label();
            label9.Text = "Tên tour";
            label9.AutoSize = true;
            label9.Dock = System.Windows.Forms.DockStyle.Fill;
            label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label9.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label9, 2, 0);
            fields7.Controls.Add(txtTen, 3, 0);
            var label10 = new System.Windows.Forms.Label();
            label10.Text = "Số ngày";
            label10.AutoSize = true;
            label10.Dock = System.Windows.Forms.DockStyle.Fill;
            label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label10.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label10, 0, 1);
            fields7.Controls.Add(numNgay, 1, 1);
            var label11 = new System.Windows.Forms.Label();
            label11.Text = "Số đêm";
            label11.AutoSize = true;
            label11.Dock = System.Windows.Forms.DockStyle.Fill;
            label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label11.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label11, 2, 1);
            fields7.Controls.Add(numDem, 3, 1);
            var label12 = new System.Windows.Forms.Label();
            label12.Text = "Đơn giá / khách";
            label12.AutoSize = true;
            label12.Dock = System.Windows.Forms.DockStyle.Fill;
            label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label12.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label12, 0, 2);
            fields7.Controls.Add(numGia, 1, 2);
            var label13 = new System.Windows.Forms.Label();
            label13.Text = "Mô tả";
            label13.AutoSize = true;
            label13.Dock = System.Windows.Forms.DockStyle.Fill;
            label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label13.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields7.Controls.Add(label13, 2, 2);
            fields7.Controls.Add(txtMoTa, 3, 2);
            layout6.Controls.Add(fields7);
            var actions14 = new System.Windows.Forms.FlowLayoutPanel();
            actions14.Dock = System.Windows.Forms.DockStyle.Top;
            actions14.AutoSize = true;
            actions14.Controls.Add(btnThemTour);
            layout6.Controls.Add(actions14);
            layout6.Controls.Add(dgvTour);
            var page15 = new System.Windows.Forms.TabPage();
            page15.Text = "Điểm dừng";
            page15.AutoScroll = true;
            tabTour.Controls.Add(page15);
            var layout16 = new System.Windows.Forms.TableLayoutPanel();
            layout16.Dock = System.Windows.Forms.DockStyle.Top;
            layout16.AutoSize = true;
            layout16.ColumnCount = 1;
            layout16.Padding = new System.Windows.Forms.Padding(12);
            layout16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page15.Controls.Add(layout16);
            var fields17 = new System.Windows.Forms.TableLayoutPanel();
            fields17.Dock = System.Windows.Forms.DockStyle.Top;
            fields17.AutoSize = true;
            fields17.ColumnCount = 4;
            fields17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label18 = new System.Windows.Forms.Label();
            label18.Text = "Thứ tự";
            label18.AutoSize = true;
            label18.Dock = System.Windows.Forms.DockStyle.Fill;
            label18.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label18.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label18, 0, 0);
            fields17.Controls.Add(numThuTu, 1, 0);
            var label19 = new System.Windows.Forms.Label();
            label19.Text = "Tên điểm dừng";
            label19.AutoSize = true;
            label19.Dock = System.Windows.Forms.DockStyle.Fill;
            label19.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label19.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label19, 2, 0);
            fields17.Controls.Add(txtDiemDung, 3, 0);
            var label20 = new System.Windows.Forms.Label();
            label20.Text = "Đổi phương tiện";
            label20.AutoSize = true;
            label20.Dock = System.Windows.Forms.DockStyle.Fill;
            label20.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label20.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label20, 0, 1);
            fields17.Controls.Add(chkDoiPT, 1, 1);
            var label21 = new System.Windows.Forms.Label();
            label21.Text = "Có nơi ăn";
            label21.AutoSize = true;
            label21.Dock = System.Windows.Forms.DockStyle.Fill;
            label21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label21.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label21, 2, 1);
            fields17.Controls.Add(chkAn, 3, 1);
            var label22 = new System.Windows.Forms.Label();
            label22.Text = "Có khách sạn";
            label22.AutoSize = true;
            label22.Dock = System.Windows.Forms.DockStyle.Fill;
            label22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label22.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label22, 0, 2);
            fields17.Controls.Add(chkKS, 1, 2);
            var label23 = new System.Windows.Forms.Label();
            label23.Text = "Hạng sao";
            label23.AutoSize = true;
            label23.Dock = System.Windows.Forms.DockStyle.Fill;
            label23.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label23.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label23, 2, 2);
            fields17.Controls.Add(numSao, 3, 2);
            var label24 = new System.Windows.Forms.Label();
            label24.Text = "Ghi chú";
            label24.AutoSize = true;
            label24.Dock = System.Windows.Forms.DockStyle.Fill;
            label24.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label24.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields17.Controls.Add(label24, 0, 3);
            fields17.Controls.Add(txtGhiChuDD, 1, 3);
            layout16.Controls.Add(fields17);
            var actions25 = new System.Windows.Forms.FlowLayoutPanel();
            actions25.Dock = System.Windows.Forms.DockStyle.Top;
            actions25.AutoSize = true;
            actions25.Controls.Add(btnThemDD);
            layout16.Controls.Add(actions25);
            layout16.Controls.Add(dgvDiemDung);
            var page26 = new System.Windows.Forms.TabPage();
            page26.Text = "Phương tiện theo chặng";
            page26.AutoScroll = true;
            tabTour.Controls.Add(page26);
            var layout27 = new System.Windows.Forms.TableLayoutPanel();
            layout27.Dock = System.Windows.Forms.DockStyle.Top;
            layout27.AutoSize = true;
            layout27.ColumnCount = 1;
            layout27.Padding = new System.Windows.Forms.Padding(12);
            layout27.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page26.Controls.Add(layout27);
            var fields28 = new System.Windows.Forms.TableLayoutPanel();
            fields28.Dock = System.Windows.Forms.DockStyle.Top;
            fields28.AutoSize = true;
            fields28.ColumnCount = 4;
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields28.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label29 = new System.Windows.Forms.Label();
            label29.Text = "Chặng thứ";
            label29.AutoSize = true;
            label29.Dock = System.Windows.Forms.DockStyle.Fill;
            label29.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label29.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label29, 0, 0);
            fields28.Controls.Add(numChang, 1, 0);
            var label30 = new System.Windows.Forms.Label();
            label30.Text = "Phương tiện";
            label30.AutoSize = true;
            label30.Dock = System.Windows.Forms.DockStyle.Fill;
            label30.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label30.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label30, 2, 0);
            fields28.Controls.Add(cboPT, 3, 0);
            var label31 = new System.Windows.Forms.Label();
            label31.Text = "Ghi chú";
            label31.AutoSize = true;
            label31.Dock = System.Windows.Forms.DockStyle.Fill;
            label31.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label31.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields28.Controls.Add(label31, 0, 1);
            fields28.Controls.Add(txtGhiChuPT, 1, 1);
            layout27.Controls.Add(fields28);
            var actions32 = new System.Windows.Forms.FlowLayoutPanel();
            actions32.Dock = System.Windows.Forms.DockStyle.Top;
            actions32.AutoSize = true;
            actions32.Controls.Add(btnThemChang);
            layout27.Controls.Add(actions32);
            layout27.Controls.Add(dgvChang);
            var page33 = new System.Windows.Forms.TabPage();
            page33.Text = "Điểm tham quan";
            page33.AutoScroll = true;
            tabTour.Controls.Add(page33);
            var layout34 = new System.Windows.Forms.TableLayoutPanel();
            layout34.Dock = System.Windows.Forms.DockStyle.Top;
            layout34.AutoSize = true;
            layout34.ColumnCount = 1;
            layout34.Padding = new System.Windows.Forms.Padding(12);
            layout34.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            page33.Controls.Add(layout34);
            var fields35 = new System.Windows.Forms.TableLayoutPanel();
            fields35.Dock = System.Windows.Forms.DockStyle.Top;
            fields35.AutoSize = true;
            fields35.ColumnCount = 4;
            fields35.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields35.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            fields35.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            fields35.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            var label36 = new System.Windows.Forms.Label();
            label36.Text = "Điểm tham quan";
            label36.AutoSize = true;
            label36.Dock = System.Windows.Forms.DockStyle.Fill;
            label36.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label36.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields35.Controls.Add(label36, 0, 0);
            fields35.Controls.Add(cboDTQ, 1, 0);
            var label37 = new System.Windows.Forms.Label();
            label37.Text = "Thứ tự";
            label37.AutoSize = true;
            label37.Dock = System.Windows.Forms.DockStyle.Fill;
            label37.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            label37.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            fields35.Controls.Add(label37, 2, 0);
            fields35.Controls.Add(numThuTuTQ, 3, 0);
            layout34.Controls.Add(fields35);
            var actions38 = new System.Windows.Forms.FlowLayoutPanel();
            actions38.Dock = System.Windows.Forms.DockStyle.Top;
            actions38.AutoSize = true;
            actions38.Controls.Add(btnThemTQ);
            layout34.Controls.Add(actions38);
            layout34.Controls.Add(dgvTQ);
            var actions39 = new System.Windows.Forms.FlowLayoutPanel();
            actions39.Dock = System.Windows.Forms.DockStyle.Top;
            actions39.AutoSize = true;
            actions39.Controls.Add(btnDong);
            layout2.Controls.Add(actions39);
            this.cboTour.SelectedIndexChanged += this.cboTour_SelectedIndexChanged;
            this.btnThemTour.Click += this.btnThemTour_Click;
            this.chkKS.CheckedChanged += this.chkKS_CheckedChanged;
            this.btnThemDD.Click += this.btnThemDD_Click;
            this.btnThemChang.Click += this.btnThemChang_Click;
            this.btnThemTQ.Click += this.btnThemTQ_Click;
            this.btnDong.Click += this.btnDong_Click;
            this.Load += this.FrmTour_Load;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.MinimumSize = new System.Drawing.Size(800, 560);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tour và hành trình";
            this.Name = "FrmTour";
            this.KeyPreview = true;
            this.KeyDown += EvidenceCapture.OnKeyDown;
            this.ResumeLayout(true);
        }
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.TabControl tabTour;
        private System.Windows.Forms.DataGridView dgvTour;
        private System.Windows.Forms.TextBox txtMa;
        private System.Windows.Forms.TextBox txtTen;
        private System.Windows.Forms.NumericUpDown numNgay;
        private System.Windows.Forms.NumericUpDown numDem;
        private System.Windows.Forms.NumericUpDown numGia;
        private System.Windows.Forms.TextBox txtMoTa;
        private System.Windows.Forms.Button btnThemTour;
        private System.Windows.Forms.DataGridView dgvDiemDung;
        private System.Windows.Forms.NumericUpDown numThuTu;
        private System.Windows.Forms.TextBox txtDiemDung;
        private System.Windows.Forms.CheckBox chkDoiPT;
        private System.Windows.Forms.CheckBox chkAn;
        private System.Windows.Forms.CheckBox chkKS;
        private System.Windows.Forms.NumericUpDown numSao;
        private System.Windows.Forms.TextBox txtGhiChuDD;
        private System.Windows.Forms.Button btnThemDD;
        private System.Windows.Forms.DataGridView dgvChang;
        private System.Windows.Forms.NumericUpDown numChang;
        private System.Windows.Forms.ComboBox cboPT;
        private System.Windows.Forms.TextBox txtGhiChuPT;
        private System.Windows.Forms.Button btnThemChang;
        private System.Windows.Forms.DataGridView dgvTQ;
        private System.Windows.Forms.ComboBox cboDTQ;
        private System.Windows.Forms.NumericUpDown numThuTuTQ;
        private System.Windows.Forms.Button btnThemTQ;
        private System.Windows.Forms.Button btnDong;
    }
}
